import numpy as np

# Auto-generated by optimization/run_full_optimization_loop.py
# Target: >5R average OOS performance
STRATEGY_CONFIG = {
    "AlphaSqueezer_V17": {
        "default": {"cooldown_seconds": 900, "confidence_threshold": 0.72, "tp_mult": 8.0, "sl_mult": 1.0, "trail_activation_r": 4.0, "trail_buffer_atr": 0.4, "max_hold_bars": 96, "vol_regime_min": -1.0},
        "ADAUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "AVAXUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "BNBUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "BTCUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "DOGEUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "DOTUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "ETHUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "LINKUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "LTCUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "NEARUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "SOLUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "SUIUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "TRXUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "XAGUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "XAUUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
        "XRPUSDT": {"confidence_threshold": 0.75, "tp_mult": 9.0, "sl_mult": 1.0, "trail_activation_r": 5.0, "trail_buffer_atr": 0.4},
    }
}

def get_param(symbol: str, strategy_name: str, param_name: str, fallback=None):
    strat_dict = STRATEGY_CONFIG.get(strategy_name)
    if not strat_dict:
        return fallback
    if symbol in strat_dict and param_name in strat_dict[symbol]:
        return strat_dict[symbol][param_name]
    if "default" in strat_dict and param_name in strat_dict["default"]:
        return strat_dict["default"][param_name]
    return fallback
