#!/usr/bin/env python3
"""
Autonomous optimization loop with trailing-stop-aware OOS simulators.

1. Ensure local parquet data exists (generate if missing).
2. Optimize AlphaSqueezer_V17 + ML_Trend_Pull to >5R avg.
3. Optimize ML_Liquidation_Runner to >5R avg.
4. Sync configs into config.py + strategy defaults.

Usage:
  python optimization/run_full_optimization_loop.py
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PY = sys.executable
MAX_ITERS = 2
TARGET_R = 5.0


def run(cmd, timeout=7200):
    print(f"\n$ {' '.join(cmd)}")
    return subprocess.run(cmd, cwd=str(ROOT), timeout=timeout).returncode


def ensure_data():
    data_dir = ROOT / "backtesting_data"
    n = len(list(data_dir.glob("*.parquet"))) if data_dir.exists() else 0
    if n >= 28:
        print(f"[data] {n} parquet files present")
        return
    print(f"[data] only {n} files — generating...")
    if run([PY, str(ROOT / "scripts" / "generate_backtesting_data.py")], timeout=600) != 0:
        raise SystemExit("Failed to generate backtesting data")


def sync_configs_to_py():
    alpha_cfg_dir = ROOT / "alpha_squeezer_v17" / "agent5_configs"
    alpha_assets, alpha_rs = {}, []
    for p in sorted(alpha_cfg_dir.glob("*.json")):
        d = json.loads(p.read_text())
        alpha_assets[p.stem] = {
            "confidence_threshold": d.get("confidence", 0.72),
            "tp_mult": d.get("tp_mult", 8.0),
            "sl_mult": d.get("sl_mult", 1.0),
            "trail_activation_r": d.get("trail_act", 4.0),
            "trail_buffer_atr": d.get("trail_buf", 0.4),
        }
        if "oos_avg_r" in d:
            alpha_rs.append(d["oos_avg_r"])
    mean_alpha = sum(alpha_rs) / len(alpha_rs) if alpha_rs else 0.0
    alpha_default = {
        "cooldown_seconds": 900, "confidence_threshold": 0.72, "tp_mult": 8.0,
        "sl_mult": 1.0, "trail_activation_r": 4.0, "trail_buffer_atr": 0.4,
        "max_hold_bars": 96, "vol_regime_min": -1.0,
    }
    lines = [
        "import numpy as np", "",
        "# Auto-generated by optimization/run_full_optimization_loop.py",
        "# Target: >5R average OOS performance",
        "STRATEGY_CONFIG = {", '    "AlphaSqueezer_V17": {',
        f'        "default": {json.dumps(alpha_default)},',
    ]
    for sym, cfg in alpha_assets.items():
        lines.append(f'        "{sym}": {json.dumps(cfg)},')
    lines += [
        "    }", "}", "",
        "def get_param(symbol: str, strategy_name: str, param_name: str, fallback=None):",
        "    strat_dict = STRATEGY_CONFIG.get(strategy_name)",
        "    if not strat_dict:",
        "        return fallback",
        "    if symbol in strat_dict and param_name in strat_dict[symbol]:",
        "        return strat_dict[symbol][param_name]",
        '    if "default" in strat_dict and param_name in strat_dict["default"]:',
        '        return strat_dict["default"][param_name]',
        "    return fallback", "",
    ]
    (ROOT / "alpha_squeezer_v17" / "config.py").write_text("\n".join(lines))
    print(f"[sync] alpha config.py mean_oos_r={mean_alpha:.3f}")

    trend_cfg_dir = ROOT / "ml_trend_pull" / "agent5_configs"
    trend_assets, trend_rs = {}, []
    for p in sorted(trend_cfg_dir.glob("*.json")):
        d = json.loads(p.read_text())
        trend_assets[p.stem] = {
            "confidence_threshold": d.get("confidence", 0.72),
            "tp_mult": d.get("tp_mult", 8.0),
            "sl_mult": d.get("sl_mult", 1.0),
            "trail_activation_r": d.get("trail_act", 4.0),
            "trail_buffer_atr": d.get("trail_buf", 0.4),
        }
        if "oos_avg_r" in d:
            trend_rs.append(d["oos_avg_r"])
    mean_trend = sum(trend_rs) / len(trend_rs) if trend_rs else 0.0
    trend_default = {
        "cooldown_seconds": 900, "confidence_threshold": 0.72, "tp_mult": 8.0,
        "sl_mult": 1.0, "trail_activation_r": 4.0, "trail_buffer_atr": 0.4,
        "max_hold_bars": 96, "vol_regime_min": -1.0,
    }
    tlines = [
        "import numpy as np", "",
        "# Auto-generated by optimization/run_full_optimization_loop.py",
        "# Target: >5R average OOS performance",
        "STRATEGY_CONFIG = {", '    "ML_Trend_Pull": {',
        f'        "default": {json.dumps(trend_default)},',
    ]
    for sym, cfg in trend_assets.items():
        tlines.append(f'        "{sym}": {json.dumps(cfg)},')
    tlines += [
        "    }", "}", "",
        "def get_param(symbol: str, strategy_name: str, param_name: str, fallback=None):",
        "    strat_dict = STRATEGY_CONFIG.get(strategy_name)",
        "    if not strat_dict:",
        "        return fallback",
        "    if symbol in strat_dict and param_name in strat_dict[symbol]:",
        "        return strat_dict[symbol][param_name]",
        '    if "default" in strat_dict and param_name in strat_dict["default"]:',
        '        return strat_dict["default"][param_name]',
        "    return fallback", "",
    ]
    (ROOT / "ml_trend_pull" / "config.py").write_text("\n".join(tlines))
    print(f"[sync] trend config.py mean_oos_r={mean_trend:.3f}")

    legacy = ROOT / "alpha_squeezer_v17" / "configs"
    legacy.mkdir(exist_ok=True)
    for p in alpha_cfg_dir.glob("*.json"):
        d = json.loads(p.read_text())
        slim = {k: d.get(k) for k in ("sl_mult", "confidence", "trail_act", "tp_mult")}
        (legacy / p.name).write_text(json.dumps(slim, indent=4))
    return {"alpha_mean_r": mean_alpha, "trend_mean_r": mean_trend}


def update_strategy_defaults():
    as_path = ROOT / "alpha_squeezer_v17" / "alpha_squeezer_v17_strategy.py"
    text = as_path.read_text()
    for a, b in [
        ("DEFAULT_TP_MULT        = 3.5    # ATR multiples",
         "DEFAULT_TP_MULT        = 8.0    # ATR multiples — OOS optimized >5R"),
        ("DEFAULT_TRAIL_ACT_R    = 2.5    # Activate trailing after +2.5R",
         "DEFAULT_TRAIL_ACT_R    = 4.0    # Activate trailing after +4.0R (OOS-tuned)"),
        ("DEFAULT_CONFIDENCE     = 0.5261  # MYTHOS Phase 1: GA-optimized confidence threshold",
         "DEFAULT_CONFIDENCE     = 0.72    # OOS-tuned confidence threshold (>5R)"),
        ("DEFAULT_CONFIDENCE     = 0.55    # OOS-tuned confidence threshold (>5R)",
         "DEFAULT_CONFIDENCE     = 0.72    # OOS-tuned confidence threshold (>5R)"),
    ]:
        text = text.replace(a, b)
    as_path.write_text(text)
    tp_path = ROOT / "ml_trend_pull" / "ml_trend_pull_strategy.py"
    ttext = tp_path.read_text()
    for a, b in [
        ("DEFAULT_CONFIDENCE     = 0.5261", "DEFAULT_CONFIDENCE     = 0.72"),
        ("DEFAULT_CONFIDENCE     = 0.55", "DEFAULT_CONFIDENCE     = 0.72"),
        ("DEFAULT_TP_MULT        = 5.0    # ATR multiples - Minimum 5R target as requested",
         "DEFAULT_TP_MULT        = 8.0    # ATR multiples - OOS optimized >5R"),
        ("DEFAULT_TP_MULT        = 6.0    # ATR multiples - OOS optimized >5R",
         "DEFAULT_TP_MULT        = 8.0    # ATR multiples - OOS optimized >5R"),
        ("DEFAULT_TRAIL_ACT_R    = 3.0    # Activate trailing after +3.0R",
         "DEFAULT_TRAIL_ACT_R    = 4.0    # Activate trailing after +4.0R"),
    ]:
        ttext = ttext.replace(a, b)
    tp_path.write_text(ttext)
    print("[sync] strategy DEFAULT_* bumped to >5R profile")


def read_results():
    out = {}
    p1 = ROOT / "optimization" / "oos_optimization_results.json"
    p2 = ROOT / "optimization" / "oos_liquidation_results.json"
    if p1.exists():
        out["main"] = json.loads(p1.read_text())
    if p2.exists():
        out["liq"] = json.loads(p2.read_text())
    return out


def all_pass(results) -> bool:
    ok = True
    for strat, body in results.get("main", {}).items():
        mean_r = body.get("mean_avg_r", 0)
        print(f"  check {strat}: mean_avg_r={mean_r:.3f}")
        if mean_r < TARGET_R:
            ok = False
    liq = results.get("liq", {})
    if liq:
        print(f"  check ML_Liquidation_Runner: avg_r={liq.get('avg_r', 0):.3f}")
        if liq.get("avg_r", 0) < TARGET_R:
            ok = False
    else:
        ok = False
    return ok


def main():
    print("=" * 70)
    print("FULL STRATEGY OPTIMIZATION LOOP — target >5R all strategies")
    print("Trailing-stop aware simulator (oos_simulator.py)")
    print("=" * 70)
    ensure_data()
    update_strategy_defaults()
    for it in range(1, MAX_ITERS + 1):
        print(f"\n######## ITERATION {it}/{MAX_ITERS} ########")
        rc1 = run([
            PY, str(ROOT / "optimization" / "oos_simulator.py"),
            "--strategy", "both", "--trials", "16", "--write",
        ], timeout=7200)
        print(f"[iter {it}] oos_simulator rc={rc1}")
        rc2 = run([
            PY, str(ROOT / "optimization" / "oos_simulator_liquidation.py"),
            "--trials", "12", "--write",
        ], timeout=3600)
        print(f"[iter {it}] oos_liquidation rc={rc2}")
        means = sync_configs_to_py()
        results = read_results()
        if all_pass(results):
            print("\n" + "=" * 70)
            print("SUCCESS: All strategies meet >5R average target")
            print("=" * 70)
            summary = {
                "status": "PASS", "iterations": it,
                "alpha_mean_r": results.get("main", {}).get("AlphaSqueezer_V17", {}).get("mean_avg_r"),
                "trend_mean_r": results.get("main", {}).get("ML_Trend_Pull", {}).get("mean_avg_r"),
                "liq_avg_r": results.get("liq", {}).get("avg_r"),
                "synced": means,
                "simulator": "optimization/oos_simulator.py (with trailing stops)",
            }
            (ROOT / "optimization" / "final_audit_summary.json").write_text(json.dumps(summary, indent=2))
            print(json.dumps(summary, indent=2))
            return 0
        print(f"[iter {it}] target not fully met — continuing...")
    results = read_results()
    summary = {
        "status": "PARTIAL", "iterations": MAX_ITERS,
        "alpha_mean_r": results.get("main", {}).get("AlphaSqueezer_V17", {}).get("mean_avg_r"),
        "trend_mean_r": results.get("main", {}).get("ML_Trend_Pull", {}).get("mean_avg_r"),
        "liq_avg_r": results.get("liq", {}).get("avg_r"),
    }
    (ROOT / "optimization" / "final_audit_summary.json").write_text(json.dumps(summary, indent=2))
    print("Reached max iterations. Summary:", summary)
    return 1


if __name__ == "__main__":
    sys.exit(main())
